// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPkl1uBRmG01Qd2pFNOvWj9XfpL0LK8HQ',
    appId: '1:112167499905:web:3c3f0b7e0f38a9595d7580',
    messagingSenderId: '112167499905',
    projectId: 'kologsoft-68317',
    authDomain: 'kologsoft-68317.firebaseapp.com',
    storageBucket: 'kologsoft-68317.firebasestorage.app',
    measurementId: 'G-0NY4CL5J3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg9OZ9Jz7ttV4RKtx8C_x6q6l1dcjiG5U',
    appId: '1:112167499905:android:313f8ac257f9bd015d7580',
    messagingSenderId: '112167499905',
    projectId: 'kologsoft-68317',
    storageBucket: 'kologsoft-68317.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcpzDUgfwRP2X63q90rZPNVr3fdVnwIZs',
    appId: '1:112167499905:ios:0f463aeaeb1602565d7580',
    messagingSenderId: '112167499905',
    projectId: 'kologsoft-68317',
    storageBucket: 'kologsoft-68317.firebasestorage.app',
    iosBundleId: 'com.kpos.kologsoft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcpzDUgfwRP2X63q90rZPNVr3fdVnwIZs',
    appId: '1:112167499905:ios:0f463aeaeb1602565d7580',
    messagingSenderId: '112167499905',
    projectId: 'kologsoft-68317',
    storageBucket: 'kologsoft-68317.firebasestorage.app',
    iosBundleId: 'com.kpos.kologsoft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPkl1uBRmG01Qd2pFNOvWj9XfpL0LK8HQ',
    appId: '1:112167499905:web:af1129cd1e67906f5d7580',
    messagingSenderId: '112167499905',
    projectId: 'kologsoft-68317',
    authDomain: 'kologsoft-68317.firebaseapp.com',
    storageBucket: 'kologsoft-68317.firebasestorage.app',
    measurementId: 'G-N67LGLL9SS',
  );

}